import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar.jsx";
import ReduxProvider from "../redux/provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Loopo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Toaster position="bottom-center" reverseOrder={false} />
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
